### ISSUE TITLE
Lucene SimpleSortedSetFacetsExample: ArrayIndexOutOfBoundsException at Packed64.get

### ISSUE THREAD

**Issue by jefferyyuan** [UltimaPhoenix/luceneappengine#4] opened 2014-11-11 15:35 UTC
Hi, Dear luceneappengine:

Thanks for this great application. 
I am trying to use Lucene DocValues in luceneappengine: but it failed with 
```java
ArrayIndexOutOfBoundsException during PerFieldDocValuesFormat$FieldsWriter.addSortedSetField.
```

I wrapped org.apache.lucene.demo.facet.SimpleSortedSetFacetsExample as a servlet: in GAE with some small change:
```java
Directory indexDir = new GaeDirectory("tmp_" + new Date().getTime());
IndexWriterConfig conf = GaeLuceneUtil.getIndexWriterConfig(
				Version.LATEST, new WhitespaceAnalyzer());

java.lang.ArrayIndexOutOfBoundsException: 15
	at org.apache.lucene.util.packed.Packed64.get(Packed64.java:124)
	at org.apache.lucene.index.MultiDocValues$OrdinalMap$1.get(MultiDocValues.java:583)
	at org.apache.lucene.codecs.DocValuesConsumer$9$1.setNext(DocValuesConsumer.java:783)
	at org.apache.lucene.codecs.DocValuesConsumer$9$1.hasNext(DocValuesConsumer.java:730)
	at org.apache.lucene.codecs.lucene410.Lucene410DocValuesConsumer.addNumericField(Lucene410DocValuesConsumer.java:159)
	at org.apache.lucene.codecs.lucene410.Lucene410DocValuesConsumer.addSortedSetField(Lucene410DocValuesConsumer.java:509)
	at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addSortedSetField(PerFieldDocValuesFormat.java:127)
	at org.apache.lucene.codecs.DocValuesConsumer.mergeSortedSetField(DocValuesConsumer.java:613)
	at org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:213)
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:122)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4173)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3768)
	at org.apache.lucene.index.SerialMergeScheduler.merge(SerialMergeScheduler.java:40)
	at org.apache.lucene.index.IndexWriter.maybeMerge(IndexWriter.java:1970)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2992)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3097)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3064)
	at org.lifelongprogrammer.tracker.test.TestFacetDocValues.index(TestFacetDocValues.java:81)
	at org.lifelongprogrammer.tracker.test.TestFacetDocValues.doGet(TestFacetDocValues.java:44)
```

**Comment by UltimaPhoenix** [comment] 2015-02-15 16:28
I was looking for it for a week and I checked bit by bit the index built by lucene with RAMDirectory against the other one built by GAEDirectory, and there are no differences. I need to go more in depth into the lucene framework in order to understand why it is not working. Any help is welcome!

PS. Sorry for the late response but recently I had some things to do that brought me far from LAE.

**Comment by UltimaPhoenix** [comment] 2016-05-05 11:21
Closing this issue for obsolescence, cannot reproduce.

**Closed by UltimaPhoenix** 2016-05-05 11:21 UTC
